### ISSUE TITLE
_bottomOffset = MediaQuery.of(context).viewInsets.bottom;

### ISSUE THREAD

**Issue by hammadparveez** [f-person/flutter_persistent_keyboard_height#3]
Not working when setting it above Material App because  
// https://stackoverflow.com/a/49271649/9714875
 _bottomOffset = MediaQuery.of(context).viewInsets.bottom;
You are getting a context that doesn't contain any MaterialApp/CupertinoApp/WidgetApp.

**Comment by f-person** [comment]
You could try to wrap the widget that needs to get the keyboard height with a `Builder` to get a new context
