### ISSUE TITLE
Is there a way to check if the keyboard is open?

### ISSUE THREAD

**Issue by LostInDarkMath** [f-person/flutter_persistent_keyboard_height#5]

**Comment by f-person** [comment]
Hi!
It's not possible with this package, as it's not in the scope

You can use [keybord_utils](https://pub.dev/documentation/keyboard_utils/latest/keyboard_utils/KeyboardUtils/isKeyboardOpen.html) for that purpose

**Comment by LostInDarkMath** [comment]
Okay, thank you for your extreme fast reply :)
