### ISSUE TITLE
Needs keyboard to be open once before getting height

### ISSUE THREAD

**Issue by utkarshgupta2504** [f-person/flutter_persistent_keyboard_height#7]
My use case was to use this package for getting scroll extent on my onboarding screen, to make way for the keyboard

On the first app run, since keyboard hasnt been opened even once, the height returned is zero

Every subsequent app open and hot restarts / reloads, will have the correct height

Any probable fixes for this?

**Comment by f-person** [comment]
Hi! I don't think we can get the keyboard height before it was ever open. Do you think using a hard-coded value if the height from the package is 0 works fine for your use case?

**Comment by utkarshgupta2504** [comment]
Yeah I also thought so, went with 44% of screen height as my hardcoded keyboard height, works well for majority cases.
